version: '{build}'

branches:
  only:
    - master

os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msvc2015
    BUILDTOOL: meson
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64
  - COMPILER: msys2
    BUILDTOOL: meson
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64
  - COMPILER: msys2
    BUILDTOOL: cmake
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: importer
    PLATFORM: x64
  - COMPILER: msvc2015
    BUILDTOOL: cmake
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64
  - COMPILER: msys2
    BUILDTOOL: cmake
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    TARGET: build
    PLATFORM: x64

install:
  - set
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'

deploy:
  provider: GitHub
  description: ''
  auth_token:
    secure: Aj9mbq43PDgYOWS4LsWkDC3UQIgPGlL8NGdUKRTRA7GZhirzOhzDyXqM7SUIk8iU
  artifact: libosmscout-importer-Windows-x86_64.zip
  on:
    branch: master
    appveyor_repo_tag: true
    target: importer

notifications:
  - provider: Email
    to:
      - tim@framstag.com
    on_build_failure: true
    on_build_status_changed: true

