version: 2
jobs:
  build:
    docker:
      - image: libosmscout/archlinux_gcc_cmake:latest
        environment:
          TZ: "/usr/share/zoneinfo/Europe/Berlin"
          LANG: "en_US.utf8"
    branches:
      only:
        - master
        - pull/*
    steps:
      - checkout
      - run:
          name: Create build directory
          command: mkdir build
      - run:
          name: Configure project
          command: cmake .. -DOSMSCOUT_BUILD_BINDING_JAVA=OFF
          working_directory: build
      - run:
          name: Build project
          command: make -j 2
          working_directory: build
      - run:
          name: Test project
          command: ctest -j 2 --output-on-failure
          working_directory: build

